
# Analisis Cuantitativo en Finanzas 2022

Addendum de read_html al final de la notebook 

Las cells anteriores sirven para ir cargando objetos necesarios o para contrastar con el método manual.

# Bonus: read_html
Otra manera provista por pandas para facilitar lo anterior

In [1]:
#url = 'http://www.rava.com/precios/panel.php?m=OPC'
#url = 'http://clasico.rava.com/precios/panel.php?m=OPC'
#url = 'http://datos.rava.com/cotizaciones/opciones'
url = 'https://iol.invertironline.com/mercado/cotizaciones/argentina/opciones/todas'
#url = 'https://www.rava.com/cotizaciones/opciones'


from bs4 import BeautifulSoup
import requests
import pandas as pd
page = requests.get(url)
soup = BeautifulSoup(page.text, 'lxml')
opciones_html = soup.find('table', {'id': 'cotizaciones'})

In [2]:
import pandas as pd
dfs = pd.read_html(url)

# dfs es una lista con un dataframe por cada tabla encontrada en la url
# si hay varias tablas en el html devolverá varios dataframes

# de la doc:
# https://pandas.pydata.org/docs/reference/api/pandas.read_html.html
# [...] This function searches for <table> elements and only for <tr> and <th> rows and 
# <td> elements within each <tr> or <th> element in the table. 
# <td> stands for “table data” [...]

print(len(dfs))
df = dfs[0]
df

1

1

### Varias maneras de especificar el acceso

In [3]:
# con el html ya cargado, como hicimos con opciones_html
pd.read_html(str(opciones_html))[0]

,Símbolo,ÚltimoOperado,VariaciónDiaria,CantidadCompra,PrecioCompra,PrecioVenta,CantidadVenta,Apertura,Mínimo,Máximo,ÚltimoCierre,MontoOperado,Unnamed: 12
0,AIGC1800DI,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
1,AIGC1800OC,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
2,AIGC2000DI,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
3,AIGC2000OC,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
4,AIGC2200DI,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2601,YPFV920.OC,2755,"0,00%",-,-,-,-,3000,2510,3000,2755,0,NaN
2602,YPFV920.SE,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
2603,YPFV960.DI,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN
2604,YPFV960.OC,3000,"0,00%",-,-,-,-,3000,3000,3000,3000,0,NaN
2605,YPFV960.SE,0,"0,00%",-,-,-,-,0,0,0,0,0,NaN

In [5]:
# por un valor especifico que conocemos dentro de la tabla
pd.read_html(url, match="YPFV920.OC", flavor="lxml")[0]

,Símbolo,ÚltimoOperado,VariaciónDiaria,CantidadCompra,PrecioCompra,PrecioVenta,CantidadVenta,Apertura,Mínimo,Máximo,ÚltimoCierre,MontoOperado,Unnamed: 12
0,AIGC1800DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
1,AIGC1800OC,0,0%,-,-,-,-,0,0,0,0,0,NaN
2,AIGC2000DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
3,AIGC2000OC,0,0%,-,-,-,-,0,0,0,0,0,NaN
4,AIGC2200DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2601,YPFV920.OC,2755,0%,-,-,-,-,3000,2510,3000,2755,0,NaN
2602,YPFV920.SE,0,0%,-,-,-,-,0,0,0,0,0,NaN
2603,YPFV960.DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
2604,YPFV960.OC,3000,0%,-,-,-,-,3000,3000,3000,3000,0,NaN
2605,YPFV960.SE,0,0%,-,-,-,-,0,0,0,0,0,NaN

In [6]:
# por id de la tabla
pd.read_html(url, attrs={"id": "cotizaciones"})[0]

,Símbolo,ÚltimoOperado,VariaciónDiaria,CantidadCompra,PrecioCompra,PrecioVenta,CantidadVenta,Apertura,Mínimo,Máximo,ÚltimoCierre,MontoOperado,Unnamed: 12
0,AIGC1800DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
1,AIGC1800OC,0,0%,-,-,-,-,0,0,0,0,0,NaN
2,AIGC2000DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
3,AIGC2000OC,0,0%,-,-,-,-,0,0,0,0,0,NaN
4,AIGC2200DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2601,YPFV920.OC,2755,0%,-,-,-,-,3000,2510,3000,2755,0,NaN
2602,YPFV920.SE,0,0%,-,-,-,-,0,0,0,0,0,NaN
2603,YPFV960.DI,0,0%,-,-,-,-,0,0,0,0,0,NaN
2604,YPFV960.OC,3000,0%,-,-,-,-,3000,3000,3000,3000,0,NaN
2605,YPFV960.SE,0,0%,-,-,-,-,0,0,0,0,0,NaN